services:
  nginx:
    container_name: nginx
    image: docker.io/nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    networks:
      - minio

  frontend:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-k-proaktive-services-mit-mein.kiel/frontend:latest
    container_name: frontend
    networks:
      - minio

  # Hinweise:
  # - MinIO ist nach dem Start unter http://localhost:9001 (Konsole) erreichbar.
  # - Zugangsdaten: minioadmin / minioadmin
  # - Die Daten werden im Ordner ./minio-data gespeichert.
  # - Init-Skripte und Startdaten können in ./minio-init abgelegt werden.
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    restart: unless-stopped
    networks:
      - minio

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./minio-init/data/User1/Documents:/data/Documents
      - ./minio-init/data/User1/Forms:/data/Forms
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set myminio http://minio:9000 minioadmin minioadmin;
        mc mb myminio/userdata;
        mc cp /data/Documents/* myminio/userdata/User1/Documents/;
        mc cp /data/Forms/* myminio/userdata/User1/Forms/;
      "
    networks:
      - minio

  forms-service:
    container_name: forms-service
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-k-proaktive-services-mit-mein.kiel/antragstellung:latest
    environment:
      - NODE_ENV=production
    depends_on:
      - minio
    networks:
      - minio

  documentservice:
    container_name: documentservice
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-k-proaktive-services-mit-mein.kiel/dokumentenverwaltung:latest
    environment:
      - NODE_ENV=production
    depends_on:
      - minio
    networks:
      - minio
  
networks:
  minio: