= Installation der Anwendung
:toc-title: Inhaltsverzeichnis
:toc:
:toclevels: 3

== Demoserver
Die Anwendung ist abrufbar auf unserem https://sp25.imn.htwk-leipzig.de[HTWK-Server]. Dort ist stets die neueste Version (der main-Branches) aller Komponenten deployed.
Das Deployment erfolgte dort mit Podman und den unveränderten Konfigurationsdateien aus diesem Repo.

== Installation
Wie auf dem Server wird die Anwendung ausschließlich mit einer Containerlaufzeit wie Podman oder Docker, und der gegebenen Compose ausgeführt.
Dabei wird angenommen, dass Docker Compose V2 oder ein kompatibles Werkzeug verwendet wird.

=== Rahmenbedingungen

- Es wird angenommen, dass Podman oder Docker sowie Docker Compose V2 bereits installiert sind. Dies ist auf verschiedenen Plattformen unterschiedlich und ist hier Out of Scope.

=== Projektverzeichnis einrichten
* ℹ️ Die folgende Ordnerstruktur und Dateien sind in diesem Repo bereits vorhanden. Falls dieses Repo also lokal geklont wurde, können die Schritte übersprungen werden und es kann mit <<start-app,Anwendung starten>> fortgefahren werden.
  ** lokal klonen: `+git clone git@gitlab.dit.htwk-leipzig.de:projekt2025-k-proaktive-services-mit-mein.kiel/server-config.git && cd server-config+`
  ** `./.env` muss verändert werden, falls ein anderer Port als `80` verwendet werden soll

**Ordner anlegen**

[source,bash]
----
mkdir kiel && cd kiel && mkdir nginx-config
---- 

**Dateien anlegen**

[source,bash]
----
touch compose.yml .env nginx-config/default.conf.template
----

**Inhalt von `./compose.yml`**
[source,text]
----
services:
  nginx:
    container_name: nginx
    image: docker.io/nginx:alpine
    ports:
      - $NGINX_PORT:$NGINX_PORT
    environment:
      - EXTERNAL_PORT=$NGINX_PORT # nginx muss den externen Port kennen, um absolute Redirect-
                                  # Antworten an den Client mit dem richtigen Port erstellen zu können
    volumes:
      - ./nginx-config:/etc/nginx/templates
    entrypoint: >
      /bin/sh -c "
        envsubst '$${EXTERNAL_PORT}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf;
        exec nginx -g 'daemon off;'
      "
    networks:
      - minio
    depends_on:
      - frontend
      - document-service
      - forms-service

  frontend:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-k-proaktive-services-mit-mein.kiel/frontend
    container_name: frontend
    networks:
      - minio

  # - Zugangsdaten: siehe .env
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - minio

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        MINIO_ROOT_USER=${MINIO_USER};
        MINIO_ROOT_PASSWORD=${MINIO_PASSWORD};

        mc alias set myminio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD};
        mc mb myminio/userdata;
      "
    networks:
      - minio

  forms-service:
    container_name: forms-service
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-k-proaktive-services-mit-mein.kiel/antragstellung
    environment:
      - NODE_ENV=production
    depends_on:
      - minio
    networks:
      - minio

  document-service:
    container_name: document-service
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2025-k-proaktive-services-mit-mein.kiel/dokumentenverwaltung
    environment:
      - NODE_ENV=production
    depends_on:
      - minio
    networks:
      - minio
  
networks:
  minio:
volumes:
  minio_data:
----

**Inhalt von `./.env`**
[source,text]
----
MINIO_USER=minioadmin
MINIO_PASSWORD=minioadmin
NGINX_PORT=80 # oder >=1024, falls rootless Containerlaufzeit genutzt wird
----

**Inhalt von `./nginx-config/default.conf.template`**
[source,text]
----
server {
    listen ${EXTERNAL_PORT};
    client_max_body_size 50M;

    location / {
        proxy_pass http://frontend:3000/;
    }

    location /documents/ {
        proxy_pass http://document-service:3001/;

        proxy_set_header X-Forwarded-Prefix /documents;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect / /documents/;
    }

    location /forms/ {
        proxy_pass http://forms-service:3000/;

        proxy_set_header X-Forwarded-Prefix /forms;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect / /forms/;
    }
}
----

[[start-app]]
=== Anwendung starten
**Authentifizierung bei der Gitlab-Container-Registry**

- Da die Repositories eine private Sichtbarkeit haben, und das DIT Gitlab grundsätzlich einen Token braucht, wird hier ein Deployment Token zur Verfügung gestellt.

Podman:
[source,bash]
----
echo "REDACTED_GITLAB_TOKEN" | podman login gitlab.dit.htwk-leipzig.de:5050 -u "kiel-deploy-token" --password-stdin
----
Docker:
[source,bash]
----
echo "REDACTED_GITLAB_TOKEN" | docker login gitlab.dit.htwk-leipzig.de:5050 -u "kiel-deploy-token" --password-stdin
----

**Container installieren und starten**

- noch immer im Ordner "kiel" aus dem vorherigen Schritt
[source,bash]
----
podman compose up -d
// oder
docker compose up -d
----
[source,bash]

=== Frontend im Browser öffnen
http://localhost:80 aufrufen (bzw. anderer Port, wenn in `.env` verändert)
