@startuml

    actor Student
    participant "Mein.Kiel" as Kiel
    participant StudentPod
    participant VermieterPod

    Student -> Kiel : Möchte Wohnsitzanmeldung machen
    Kiel -> StudentPod : Sucht Verweis auf Adresse
    StudentPod --> Kiel : Adressenverweis
    Kiel -> VermieterPod : Nutzt Adressenverweis auf Vermieter Merkmal \n , um Adresse zu lesen
    VermieterPod --> Kiel : Adresse
    Kiel -> Kiel : Nutzt Adresse für Wohnsitzanmeldung
    Student -> Kiel : Schließt Vorgang ab
    Kiel --> Student : Erfolgsmeldung

@enduml